# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octopusgarden < Formula
  desc "Autonomous software dark factory: specs to working code via attractor loop"
  homepage "https://github.com/foundatron/octopusgarden"
  version "2.68.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.68.2/octopusgarden_2.68.2_darwin_amd64.tar.gz"
      sha256 "73f918bcd9d7de31ac031026e6ebd09d5ae9bcd1cf938d9b943026252baba584"

      define_method(:install) do
        bin.install "octog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.68.2/octopusgarden_2.68.2_darwin_arm64.tar.gz"
      sha256 "d1320c0b28fe167c24bd56c3f96d8cb38512fdd62921b386c6c8501b1892caf8"

      define_method(:install) do
        bin.install "octog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.68.2/octopusgarden_2.68.2_linux_amd64.tar.gz"
      sha256 "5b5c6f63716e358b9fd0642cfecd37612c97595e1b443fcc68cedec582ebdae0"
      define_method(:install) do
        bin.install "octog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.68.2/octopusgarden_2.68.2_linux_arm64.tar.gz"
      sha256 "ea236b45d8bf8b2977be21f608dea49c8de19cf352bfb83d1d6f8e28b1b3a382"
      define_method(:install) do
        bin.install "octog"
      end
    end
  end

  test do
    system "#{bin}/octog", "--version"
  end
end
