# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octopusgarden < Formula
  desc "Autonomous software dark factory: specs to working code via attractor loop"
  homepage "https://github.com/foundatron/octopusgarden"
  version "2.69.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.69.0/octopusgarden_2.69.0_darwin_amd64.tar.gz"
      sha256 "1e87636daef7cbaea03359e32d550cdccf85fac324b85676035bae6b442417b0"

      define_method(:install) do
        bin.install "octog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.69.0/octopusgarden_2.69.0_darwin_arm64.tar.gz"
      sha256 "b91357bb3e53037efebaa0f62bd81c52a7469dd538dcc20366356c714bfc2a7d"

      define_method(:install) do
        bin.install "octog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.69.0/octopusgarden_2.69.0_linux_amd64.tar.gz"
      sha256 "0953b7bf3ebce345355c22351295a175d396a0b28401975167fc62ad94467927"
      define_method(:install) do
        bin.install "octog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundatron/octopusgarden/releases/download/v2.69.0/octopusgarden_2.69.0_linux_arm64.tar.gz"
      sha256 "6687690c13eb405c90aab9e7f8ab5215e399f35d95299c240b7a0652f87fba74"
      define_method(:install) do
        bin.install "octog"
      end
    end
  end

  test do
    system "#{bin}/octog", "--version"
  end
end
